// 
// Decompiled by Procyon v0.5.30
// 

package com.jetbrains.cidr.execution.debugger.backend.lldb.auto_generated;

import com.google.protobuf.GeneratedMessage;
import com.google.protobuf.ExtensionRegistry;
import com.google.protobuf.Descriptors;

static final class Protocol$1 implements Descriptors.FileDescriptor.InternalDescriptorAssigner {
    public ExtensionRegistry assignDescriptors(final Descriptors.FileDescriptor fileDescriptor) {
        Protocol.access$73602(fileDescriptor);
        Protocol.access$002(Protocol.getDescriptor().getMessageTypes().get(0));
        Protocol.access$102(new GeneratedMessage.FieldAccessorTable(Protocol.access$000(), new String[] { "IsValid", "ErrorMessage" }));
        Protocol.access$1002(Protocol.getDescriptor().getMessageTypes().get(1));
        Protocol.access$1102(new GeneratedMessage.FieldAccessorTable(Protocol.access$1000(), new String[] { "ExePath", "Arch", "RemoteExePath", "Platform", "PlatformSdkRoot" }));
        Protocol.access$2302(Protocol.getDescriptor().getMessageTypes().get(2));
        Protocol.access$2402(new GeneratedMessage.FieldAccessorTable(Protocol.access$2300(), new String[] { "CommonResponse" }));
        Protocol.access$3202(Protocol.getDescriptor().getMessageTypes().get(3));
        Protocol.access$3302(new GeneratedMessage.FieldAccessorTable(Protocol.access$3200(), new String[] { "CommandLine", "FdPassingServiceUnixSocket" }));
        Protocol.access$4202(Protocol.getDescriptor().getMessageTypes().get(4));
        Protocol.access$4302(new GeneratedMessage.FieldAccessorTable(Protocol.access$4200(), new String[] { "CommonResponse", "Pid" }));
        Protocol.access$5202(Protocol.getDescriptor().getMessageTypes().get(5));
        Protocol.access$5302(new GeneratedMessage.FieldAccessorTable(Protocol.access$5200(), new String[] { "Name", "ToWait" }));
        Protocol.access$6202(Protocol.getDescriptor().getMessageTypes().get(6));
        Protocol.access$6302(new GeneratedMessage.FieldAccessorTable(Protocol.access$6200(), new String[] { "CommonResponse" }));
        Protocol.access$7102(Protocol.getDescriptor().getMessageTypes().get(7));
        Protocol.access$7202(new GeneratedMessage.FieldAccessorTable(Protocol.access$7100(), new String[] { "Pid" }));
        Protocol.access$8002(Protocol.getDescriptor().getMessageTypes().get(8));
        Protocol.access$8102(new GeneratedMessage.FieldAccessorTable(Protocol.access$8000(), new String[0]));
        Protocol.access$8702(Protocol.getDescriptor().getMessageTypes().get(9));
        Protocol.access$8802(new GeneratedMessage.FieldAccessorTable(Protocol.access$8700(), new String[] { "CommonResponse" }));
        Protocol.access$9602(Protocol.getDescriptor().getMessageTypes().get(10));
        Protocol.access$9702(new GeneratedMessage.FieldAccessorTable(Protocol.access$9600(), new String[0]));
        Protocol.access$10302(Protocol.getDescriptor().getMessageTypes().get(11));
        Protocol.access$10402(new GeneratedMessage.FieldAccessorTable(Protocol.access$10300(), new String[] { "CommonResponse" }));
        Protocol.access$11202(Protocol.getDescriptor().getMessageTypes().get(12));
        Protocol.access$11302(new GeneratedMessage.FieldAccessorTable(Protocol.access$11200(), new String[] { "CommonResponse" }));
        Protocol.access$12102(Protocol.getDescriptor().getMessageTypes().get(13));
        Protocol.access$12202(new GeneratedMessage.FieldAccessorTable(Protocol.access$12100(), new String[0]));
        Protocol.access$12802(Protocol.getDescriptor().getMessageTypes().get(14));
        Protocol.access$12902(new GeneratedMessage.FieldAccessorTable(Protocol.access$12800(), new String[] { "CommonResponse" }));
        Protocol.access$13702(Protocol.getDescriptor().getMessageTypes().get(15));
        Protocol.access$13802(new GeneratedMessage.FieldAccessorTable(Protocol.access$13700(), new String[0]));
        Protocol.access$14402(Protocol.getDescriptor().getMessageTypes().get(16));
        Protocol.access$14502(new GeneratedMessage.FieldAccessorTable(Protocol.access$14400(), new String[] { "CommonResponse" }));
        Protocol.access$15302(Protocol.getDescriptor().getMessageTypes().get(17));
        Protocol.access$15402(new GeneratedMessage.FieldAccessorTable(Protocol.access$15300(), new String[0]));
        Protocol.access$16002(Protocol.getDescriptor().getMessageTypes().get(18));
        Protocol.access$16102(new GeneratedMessage.FieldAccessorTable(Protocol.access$16000(), new String[] { "CommonResponse", "Thread" }));
        Protocol.access$17102(Protocol.getDescriptor().getMessageTypes().get(19));
        Protocol.access$17202(new GeneratedMessage.FieldAccessorTable(Protocol.access$17100(), new String[] { "ThreadId", "FromIndex", "Count", "UntilValidLineEntry" }));
        Protocol.access$18302(Protocol.getDescriptor().getMessageTypes().get(20));
        Protocol.access$18402(new GeneratedMessage.FieldAccessorTable(Protocol.access$18300(), new String[] { "CommonResponse", "Frame", "HasMore" }));
        Protocol.access$19502(Protocol.getDescriptor().getMessageTypes().get(21));
        Protocol.access$19602(new GeneratedMessage.FieldAccessorTable(Protocol.access$19500(), new String[] { "File", "Line", "Condition", "SymbolPattern", "ModuleName", "ThreadId", "Regexp" }));
        Protocol.access$21002(Protocol.getDescriptor().getMessageTypes().get(22));
        Protocol.access$21102(new GeneratedMessage.FieldAccessorTable(Protocol.access$21000(), new String[] { "Id" }));
        Protocol.access$21902(Protocol.getDescriptor().getMessageTypes().get(23));
        Protocol.access$22002(new GeneratedMessage.FieldAccessorTable(Protocol.access$21900(), new String[] { "CommonResponse" }));
        Protocol.access$22802(Protocol.getDescriptor().getMessageTypes().get(24));
        Protocol.access$22902(new GeneratedMessage.FieldAccessorTable(Protocol.access$22800(), new String[] { "CommonResponse", "Id" }));
        Protocol.access$23802(Protocol.getDescriptor().getMessageTypes().get(25));
        Protocol.access$23902(new GeneratedMessage.FieldAccessorTable(Protocol.access$23800(), new String[] { "ThreadId" }));
        Protocol.access$24702(Protocol.getDescriptor().getMessageTypes().get(26));
        Protocol.access$24802(new GeneratedMessage.FieldAccessorTable(Protocol.access$24700(), new String[] { "CommonResponse" }));
        Protocol.access$25602(Protocol.getDescriptor().getMessageTypes().get(27));
        Protocol.access$25702(new GeneratedMessage.FieldAccessorTable(Protocol.access$25600(), new String[] { "ThreadId" }));
        Protocol.access$26502(Protocol.getDescriptor().getMessageTypes().get(28));
        Protocol.access$26602(new GeneratedMessage.FieldAccessorTable(Protocol.access$26500(), new String[] { "CommonResponse" }));
        Protocol.access$27402(Protocol.getDescriptor().getMessageTypes().get(29));
        Protocol.access$27502(new GeneratedMessage.FieldAccessorTable(Protocol.access$27400(), new String[] { "ThreadId" }));
        Protocol.access$28302(Protocol.getDescriptor().getMessageTypes().get(30));
        Protocol.access$28402(new GeneratedMessage.FieldAccessorTable(Protocol.access$28300(), new String[] { "CommonResponse" }));
        Protocol.access$29202(Protocol.getDescriptor().getMessageTypes().get(31));
        Protocol.access$29302(new GeneratedMessage.FieldAccessorTable(Protocol.access$29200(), new String[] { "Expression", "ThreadId", "FrameIndex", "Language" }));
        Protocol.access$30402(Protocol.getDescriptor().getMessageTypes().get(32));
        Protocol.access$30502(new GeneratedMessage.FieldAccessorTable(Protocol.access$30400(), new String[] { "CommonResponse", "Result" }));
        Protocol.access$31402(Protocol.getDescriptor().getMessageTypes().get(33));
        Protocol.access$31502(new GeneratedMessage.FieldAccessorTable(Protocol.access$31400(), new String[] { "ValueId", "ToResolveLocation", "Read", "Write", "Condition" }));
        Protocol.access$32702(Protocol.getDescriptor().getMessageTypes().get(34));
        Protocol.access$32802(new GeneratedMessage.FieldAccessorTable(Protocol.access$32700(), new String[] { "Id" }));
        Protocol.access$33602(Protocol.getDescriptor().getMessageTypes().get(35));
        Protocol.access$33702(new GeneratedMessage.FieldAccessorTable(Protocol.access$33600(), new String[] { "CommonResponse" }));
        Protocol.access$34502(Protocol.getDescriptor().getMessageTypes().get(36));
        Protocol.access$34602(new GeneratedMessage.FieldAccessorTable(Protocol.access$34500(), new String[] { "CommonResponse", "WatchpointId" }));
        Protocol.access$35502(Protocol.getDescriptor().getMessageTypes().get(37));
        Protocol.access$35602(new GeneratedMessage.FieldAccessorTable(Protocol.access$35500(), new String[] { "Id", "Expression", "Offset", "Count" }));
        Protocol.access$36702(Protocol.getDescriptor().getMessageTypes().get(38));
        Protocol.access$36802(new GeneratedMessage.FieldAccessorTable(Protocol.access$36700(), new String[] { "ValueId", "Offset", "Count" }));
        Protocol.access$37802(Protocol.getDescriptor().getMessageTypes().get(39));
        Protocol.access$37902(new GeneratedMessage.FieldAccessorTable(Protocol.access$37800(), new String[] { "CommonResponse", "Value" }));
        Protocol.access$38902(Protocol.getDescriptor().getMessageTypes().get(40));
        Protocol.access$39002(new GeneratedMessage.FieldAccessorTable(Protocol.access$38900(), new String[] { "Id", "MaxDescriptionLength" }));
        Protocol.access$39902(Protocol.getDescriptor().getMessageTypes().get(41));
        Protocol.access$40002(new GeneratedMessage.FieldAccessorTable(Protocol.access$39900(), new String[] { "CommonResponse", "Value" }));
        Protocol.access$40902(Protocol.getDescriptor().getMessageTypes().get(42));
        Protocol.access$41002(new GeneratedMessage.FieldAccessorTable(Protocol.access$40900(), new String[] { "Id", "MaxLength" }));
        Protocol.access$41902(Protocol.getDescriptor().getMessageTypes().get(43));
        Protocol.access$42002(new GeneratedMessage.FieldAccessorTable(Protocol.access$41900(), new String[] { "CommonResponse", "Description" }));
        Protocol.access$42902(Protocol.getDescriptor().getMessageTypes().get(44));
        Protocol.access$43002(new GeneratedMessage.FieldAccessorTable(Protocol.access$42900(), new String[] { "Id", "Expression" }));
        Protocol.access$43902(Protocol.getDescriptor().getMessageTypes().get(45));
        Protocol.access$44002(new GeneratedMessage.FieldAccessorTable(Protocol.access$43900(), new String[] { "CommonResponse", "Count" }));
        Protocol.access$44902(Protocol.getDescriptor().getMessageTypes().get(46));
        Protocol.access$45002(new GeneratedMessage.FieldAccessorTable(Protocol.access$44900(), new String[] { "CommonResponse", "Value" }));
        Protocol.access$46002(Protocol.getDescriptor().getMessageTypes().get(47));
        Protocol.access$46102(new GeneratedMessage.FieldAccessorTable(Protocol.access$46000(), new String[] { "ThreadId", "FrameIndex", "Statics", "Globals" }));
        Protocol.access$47202(Protocol.getDescriptor().getMessageTypes().get(48));
        Protocol.access$47302(new GeneratedMessage.FieldAccessorTable(Protocol.access$47200(), new String[] { "CommonResponse", "Value" }));
        Protocol.access$48302(Protocol.getDescriptor().getMessageTypes().get(49));
        Protocol.access$48402(new GeneratedMessage.FieldAccessorTable(Protocol.access$48300(), new String[] { "Input", "Target" }));
        Protocol.access$49302(Protocol.getDescriptor().getMessageTypes().get(50));
        Protocol.access$49402(new GeneratedMessage.FieldAccessorTable(Protocol.access$49300(), new String[] { "CommonResponse" }));
        Protocol.access$50202(Protocol.getDescriptor().getMessageTypes().get(51));
        Protocol.access$50302(new GeneratedMessage.FieldAccessorTable(Protocol.access$50200(), new String[] { "ThreadId", "FrameIndex", "Command" }));
        Protocol.access$51302(Protocol.getDescriptor().getMessageTypes().get(52));
        Protocol.access$51402(new GeneratedMessage.FieldAccessorTable(Protocol.access$51300(), new String[] { "CommonResponse", "Success", "Err", "Out" }));
        Protocol.access$52502(Protocol.getDescriptor().getMessageTypes().get(53));
        Protocol.access$52602(new GeneratedMessage.FieldAccessorTable(Protocol.access$52500(), new String[] { "Command", "Pos" }));
        Protocol.access$53502(Protocol.getDescriptor().getMessageTypes().get(54));
        Protocol.access$53602(new GeneratedMessage.FieldAccessorTable(Protocol.access$53500(), new String[] { "CommonResponse", "Completion" }));
        Protocol.access$54502(Protocol.getDescriptor().getMessageTypes().get(55));
        Protocol.access$54602(new GeneratedMessage.FieldAccessorTable(Protocol.access$54500(), new String[] { "FilterEnabled" }));
        Protocol.access$55402(Protocol.getDescriptor().getMessageTypes().get(56));
        Protocol.access$55502(new GeneratedMessage.FieldAccessorTable(Protocol.access$55400(), new String[] { "CommonResponse" }));
        Protocol.access$56302(Protocol.getDescriptor().getMessageTypes().get(57));
        Protocol.access$56402(new GeneratedMessage.FieldAccessorTable(Protocol.access$56300(), new String[] { "Platform", "Url" }));
        Protocol.access$57302(Protocol.getDescriptor().getMessageTypes().get(58));
        Protocol.access$57402(new GeneratedMessage.FieldAccessorTable(Protocol.access$57300(), new String[] { "CommonResponse" }));
        Protocol.access$58202(Protocol.getDescriptor().getMessageTypes().get(59));
        Protocol.access$58302(new GeneratedMessage.FieldAccessorTable(Protocol.access$58200(), new String[0]));
        Protocol.access$58902(Protocol.getDescriptor().getMessageTypes().get(60));
        Protocol.access$59002(new GeneratedMessage.FieldAccessorTable(Protocol.access$58900(), new String[] { "Id" }));
        Protocol.access$59802(Protocol.getDescriptor().getMessageTypes().get(61));
        Protocol.access$59902(new GeneratedMessage.FieldAccessorTable(Protocol.access$59800(), new String[] { "CommonResponse", "Address" }));
        Protocol.access$60802(Protocol.getDescriptor().getMessageTypes().get(62));
        Protocol.access$60902(new GeneratedMessage.FieldAccessorTable(Protocol.access$60800(), new String[] { "Signal", "Stop", "Pass", "Notify" }));
        Protocol.access$62002(Protocol.getDescriptor().getMessageTypes().get(63));
        Protocol.access$62102(new GeneratedMessage.FieldAccessorTable(Protocol.access$62000(), new String[] { "CommonResponse" }));
        Protocol.access$62902(Protocol.getDescriptor().getMessageTypes().get(64));
        Protocol.access$63002(new GeneratedMessage.FieldAccessorTable(Protocol.access$62900(), new String[] { "Command", "WorkingDir", "TimeoutSecs" }));
        Protocol.access$64002(Protocol.getDescriptor().getMessageTypes().get(65));
        Protocol.access$64102(new GeneratedMessage.FieldAccessorTable(Protocol.access$64000(), new String[] { "CommonResponse", "Output", "Status", "Signal" }));
        Protocol.access$65202(Protocol.getDescriptor().getMessageTypes().get(66));
        Protocol.access$65302(new GeneratedMessage.FieldAccessorTable(Protocol.access$65200(), new String[] { "CreateTarget", "Launch", "Exit", "Continue", "Suspend", "GetThreads", "GetFrames", "AddBreakpoint", "RemoveBreakpoint", "StepInto", "StepOver", "StepOut", "EvaluateExpression", "GetValueChildren", "GetVars", "HandleConsoleCommand", "HandleCompletion", "Attach", "AttachByName", "DispatchInput", "AddWatchpoint", "RemoveWatchpoint", "Detach", "Kill", "GetChildrenCount", "GetArraySlice", "GetValueData", "GetValueDescription", "ValuesFilteringPolicy", "ConnectPlatform", "GetValueAddress", "HandleSignal", "ExecuteShellCommand" }));
        Protocol.access$69402(Protocol.getDescriptor().getMessageTypes().get(67));
        Protocol.access$69502(new GeneratedMessage.FieldAccessorTable(Protocol.access$69400(), new String[] { "CreateTarget", "Launch", "Continue", "CompositeBroadcast", "Suspend", "GetThreads", "GetFrames", "AddBreakpoint", "RemoveBreakpoint", "StepInto", "StepOver", "StepOut", "EvaluateExpression", "GetValueChildren", "GetVars", "HandleConsoleCommand", "HandleCompletion", "Attach", "AttachByName", "DispatchInput", "AddWatchpoint", "RemoveWatchpoint", "Detach", "Kill", "GetChildrenCount", "GetArraySlice", "GetValueData", "GetValueDescription", "ValuesFilteringPolicy", "ConnectPlatform", "GetValueAddress", "HandleSignal", "ExecuteShellCommand" }));
        return null;
    }
}